# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c4f21e37943f1a0018c2993cf9be649ef8e77b74c663cca70fa5a8b728627c6ac3a8039c0f08829229a2f809f04f514437436cd40d901afd638434d0239bb50

test:
  secret_key_base: 7b9086db9758ccc3dd21f3a23491ad830c72f957c04cf494f356ef704779cd5c1676755da67a4104d48a8eb2a949b18fe574820340d82ae5d94d6cc07302858a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
